### ISSUE TITLE
Change to faster terminal

### ISSUE THREAD

**Issue by TheMoominTroll** [Eclipsu/dotfiles#1]
Use [Alacrity](https://github.com/alacritty/alacritty) or [Kitty](https://github.com/kovidgoyal/kitty)

Also Neofetch not showing.

Just do this ( Also configure neofetch Looks bloated)

> # Neofetch :see_no_evil: :hear_no_evil: :speak_no_evil:
![Neofetch](https://raw.githubusercontent.com/Eclipsu/dotfiles/master/zsh/zsh_ss.png)

**Comment by TheMoominTroll** [comment]
If u are gonna use kitty : https://sw.kovidgoyal.net/kitty/#zsh

Also read more of that kitty docs on the website : https://sw.kovidgoyal.net/kitty/

As of now : kitty is fastest known linux terminal.

**Comment by TheMoominTroll** [comment]
![image](https://user-images.githubusercontent.com/70548117/117907291-425ca980-b2f6-11eb-9a69-f833bb7a579b.png)

**Comment by TheMoominTroll** [comment]
Just change that to README.md to this 
`> # Neofetch :see_no_evil: :hear_no_evil: :speak_no_evil:
![Neofetch](https://raw.githubusercontent.com/Eclipsu/dotfiles/master/zsh/zsh_ss.png)`

**Comment by TheMoominTroll** [comment]
<p align="center" style="color:red;">@Eclipsu You might also want to set up zsh in your android</p>
<h2 align="center"> <img src="https://f-droid.org/repo/com.termux/en-US/icon_7jMZ7XD80oeucmGEaTwktIRZexLtGWvJfKdVD6Wu2SI=.png"></h2>
<h1 align="center"><a href="https://termux.com/">TERMUX</a></h1>

![#9400D3](https://via.placeholder.com/15/9400D3/000000?text=+)![#4B0082](https://via.placeholder.com/15/4B0082/000000?text=+)![0000FF](https://via.placeholder.com/15/0000FF/000000?text=+)![00FF00](https://via.placeholder.com/15/00FF00/000000?text=+)![FFFF00](https://via.placeholder.com/15/FFFF00/000000?text=+)![FF7F00](https://via.placeholder.com/15/FF7F00/000000?text=+)![FF0000](https://via.placeholder.com/15/FF0000/000000?text=+)

![#9400D3](https://via.placeholder.com/15/9400D3/000000?text=+)![#4B0082](https://via.placeholder.com/15/4B0082/000000?text=+)![0000FF](https://via.placeholder.com/15/0000FF/000000?text=+)![00FF00](https://via.placeholder.com/15/00FF00/000000?text=+)![FFFF00](https://via.placeholder.com/15/FFFF00/000000?text=+)![FF7F00](https://via.placeholder.com/15/FF7F00/000000?text=+)![FF0000](https://via.placeholder.com/15/FF0000/000000?text=+)

**Comment by Eclipsu** [comment]
Nice! But i don't know why would i need to use zsh in my android 👀

**Comment by TheMoominTroll** [comment]
@Eclipsu README.md is still not fixed 
instead of <h3> you can use ### in markdown
Most of the markdown elements require one spacing above or below to work properly with html tags.

U would want to use terminal with zsh in android so that u can access your laptop or remote server through ssh and access the files.
Also u can PRoot into installing fully working linux distro on yout phone.
You can also code and run files on android.
